# Complete Pandas Cheat Sheet

Every code line has an inline comment explaining what it does.
Run cells top to bottom — later sections assume `df`, `df2`, and `s` exist from earlier cells.

In [1]:
import pandas as pd          # standard import alias for pandas
import numpy as np           # numpy is commonly used alongside pandas

## 1. Creating Data Structures

In [2]:
s = pd.Series([1, 2, 3, 4])                          # create a 1D labeled array (Series)
s = pd.Series([1, 2, 3], index=['a', 'b', 'c'])      # Series with custom index labels

df = pd.DataFrame({                                   # create a DataFrame from a dict of lists
    'name': ['Ali', 'Sara', 'Zain'],
    'age': [22, 25, 19],
    'city': ['Lahore', 'Karachi', 'Multan']
})

df = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])  # DataFrame from random numpy array

df2 = pd.DataFrame([[1, 2], [3, 4]], columns=['x', 'y'])  # DataFrame from a list of lists
df

          A         B         C
0  1.353720 -0.503074  2.135811
1 -0.766425 -1.879786 -0.155473
2 -1.087383  0.968508 -1.257942
3  0.191624 -0.454685 -2.531363
4  1.764822 -1.902340  0.124852

## 2. Reading & Writing Data

In [3]:
# df = pd.read_csv('file.csv')                          # read a CSV file into a DataFrame
# df = pd.read_csv('file.csv', index_col=0)              # read CSV and set first column as index
# df = pd.read_excel('file.xlsx', sheet_name='Sheet1')    # read an Excel sheet into a DataFrame
# df = pd.read_json('file.json')                          # read a JSON file into a DataFrame
# df = pd.read_sql('SELECT * FROM table', con=connection) # read data from a SQL query
# df = pd.read_parquet('file.parquet')                    # read a Parquet file

# df.to_csv('out.csv', index=False)                      # write DataFrame to CSV (no row index column)
# df.to_excel('out.xlsx', index=False)                    # write DataFrame to Excel file
# df.to_json('out.json')                                  # write DataFrame to JSON file
# df.to_parquet('out.parquet')                            # write DataFrame to Parquet file

## 3. Inspecting Data

In [4]:
df.head()                 # show first 5 rows
df.head(10)                # show first 10 rows
df.tail()                  # show last 5 rows
df.shape                   # (rows, columns) tuple
df.info()                  # summary: dtypes, non-null counts, memory usage
df.describe()               # summary statistics for numeric columns
df.dtypes                  # data type of each column
df.columns                 # list of column names
df.index                   # index (row labels) of the DataFrame
df.values                  # underlying numpy array of the data
df.memory_usage()           # memory usage of each column
df.nunique()                # number of unique values per column
df.count()                  # count of non-null values per column
df.sample(3)                 # randomly sample rows

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
dtypes: float64(3)
memory usage: 252.0 bytes

          A         B         C
1 -0.766425 -1.879786 -0.155473
2 -1.087383  0.968508 -1.257942
4  1.764822 -1.902340  0.124852

## 4. Selecting / Indexing Data

In [5]:
df = pd.DataFrame({
    'name': ['Ali', 'Sara', 'Zain'],
    'age': [22, 25, 19],
    'city': ['Lahore', 'Karachi', 'Multan']
})

df['name']                     # select a single column (returns Series)
df[['name', 'age']]              # select multiple columns (returns DataFrame)
df.iloc[0]                      # select row by integer position
df.iloc[0:3]                     # select rows 0 to 2 by position
df.iloc[0, 1]                    # select value at row 0, column 1 by position
df.loc[0]                        # select row by label
df.loc[0:2, 'name']               # select rows 0-2, column 'name' by label
df.loc[df['age'] > 20]              # boolean indexing: rows where age > 20
df.at[0, 'name']                   # fast scalar access by label (single value)
df.iat[0, 1]                       # fast scalar access by integer position
df.query('age > 20')                # select rows using a query string
df.filter(items=['name', 'age'])      # select specific columns by name
df.filter(like='a')                   # select columns whose names contain 'a'
df.filter(regex='^n')                  # select columns matching a regex pattern

   name
0   Ali
1  Sara
2  Zain

## 5. Filtering / Boolean Conditions

In [6]:
df[df['age'] > 20]                          # rows where age is greater than 20
df[(df['age'] > 20) & (df['city'] == 'Lahore')]  # multiple conditions (AND)
df[(df['age'] > 20) | (df['age'] < 18)]          # multiple conditions (OR)
df[df['city'].isin(['Lahore', 'Karachi'])]        # rows where city is in a list
df[~df['city'].isin(['Lahore'])]                   # negate a condition (NOT)
df[df['name'].str.contains('a')]                    # rows where string column contains substring
df[df['age'].between(18, 25)]                        # rows where value falls within a range

   name  age     city
0   Ali   22   Lahore
1  Sara   25  Karachi
2  Zain   19   Multan

## 6. Modifying Data

In [7]:
df['age'] = df['age'] + 1                      # modify an existing column
df['is_adult'] = df['age'] >= 18                 # create a new column from a condition
df['full_info'] = df['name'] + ' - ' + df['city']  # combine columns into a new one
df.rename(columns={'name': 'full_name'})           # rename column(s)
df.rename(index={0: 'first'})                        # rename row index label(s)
df.drop(columns=['city'])                              # drop a column
df.drop(index=[0])                                      # drop a row by index label
df.drop_duplicates()                                     # remove duplicate rows
df.drop_duplicates(subset=['name'])                        # remove duplicates based on specific column
df.reset_index(drop=True)                                   # reset index to default integers
df.set_index('name')                                          # set a column as the new index
df.sort_values('age')                                           # sort rows by column value (ascending)
df.sort_values('age', ascending=False)                            # sort descending
df.sort_index()                                                     # sort rows by index
df.T                                                                 # transpose rows and columns

                      0               1              2
name                Ali            Sara           Zain
age                  23              26             20
city             Lahore         Karachi         Multan
is_adult           True            True           True
full_info  Ali - Lahore  Sara - Karachi  Zain - Multan

## 7. Handling Missing Data

In [8]:
df.isnull()                       # boolean DataFrame: True where value is NaN
df.isnull().sum()                   # count of missing values per column
df.notnull()                         # boolean DataFrame: True where value is NOT NaN
df.dropna()                           # drop rows with any missing values
df.dropna(axis=1)                       # drop columns with any missing values
df.dropna(how='all')                     # drop rows only if ALL values are missing
df.fillna(0)                               # fill missing values with 0
df.fillna(df.mean(numeric_only=True))        # fill missing values with column mean
df.ffill()                                     # forward-fill missing values
df.bfill()                                       # backward-fill missing values
df.select_dtypes(include='number').interpolate()  # fill missing numeric values using interpolation

   age
0   23
1   26
2   20

## 8. Grouping & Aggregation

In [9]:
df.groupby('city')                                  # group DataFrame by column values
df.groupby('city').mean(numeric_only=True)             # mean of each group
df.groupby('city')['age'].sum()                           # sum of 'age' per group
df.groupby('city').agg({'age': 'mean', 'name': 'count'})     # multiple aggregations per column
df.groupby(['city', 'is_adult']).size()                        # group by multiple columns, count rows
df.groupby('city').apply(lambda x: x['age'].max())               # custom aggregation function
df.pivot_table(values='age', index='city', aggfunc='mean')         # pivot table with aggregation
df.pivot(index='name', columns='city', values='age')                 # reshape data (pivot)

city  Karachi  Lahore  Multan
name
Ali       NaN    23.0     NaN
Sara     26.0     NaN     NaN
Zain      NaN     NaN    20.0

## 9. Merging / Joining / Concatenating

In [10]:
df_a = pd.DataFrame({'id': [1, 2, 3], 'val': ['a', 'b', 'c']})
df_b = pd.DataFrame({'id': [2, 3, 4], 'score': [90, 80, 70]})

pd.concat([df_a, df_b], axis=0)                          # stack DataFrames vertically (row-wise)
pd.concat([df_a, df_b], axis=1)                            # stack DataFrames horizontally (column-wise)
pd.merge(df_a, df_b, on='id')                                # SQL-style inner join on a common column
pd.merge(df_a, df_b, on='id', how='left')                       # left join (keep all rows from df_a)
pd.merge(df_a, df_b, on='id', how='right')                        # right join (keep all rows from df_b)
pd.merge(df_a, df_b, on='id', how='outer')                          # outer join (keep all rows from both)
df_a.join(df_b.set_index('id'), on='id')                              # join on index instead of column

   id val  score
0   1   a    NaN
1   2   b   90.0
2   3   c   80.0

## 10. Applying Functions

In [11]:
df['age'].apply(lambda x: x * 2)                    # apply function to each value in a column
df.apply(lambda row: row['age'] + 1, axis=1)          # apply function across each row
df.map(lambda x: str(x))                                # apply function to every element in DataFrame
df['name'].map({'Ali': 'A', 'Sara': 'S'})                  # map values using a dictionary
df['name'].str.upper()                                       # convert strings to uppercase
df['name'].str.lower()                                         # convert strings to lowercase
df['name'].str.strip()                                           # remove leading/trailing whitespace
df['name'].str.replace('a', 'A')                                   # replace substring in strings
df['name'].str.split(' ')                                            # split strings into lists
df['name'].str.len()                                                   # length of each string

0    3
1    4
2    4
Name: name, dtype: int64

## 11. Date & Time Handling

In [12]:
df['date'] = pd.date_range('2024-01-01', periods=len(df))  # add a sample date column

df['date'] = pd.to_datetime(df['date'])              # convert column to datetime type
df['year'] = df['date'].dt.year                        # extract year from datetime column
df['month'] = df['date'].dt.month                        # extract month from datetime column
df['day'] = df['date'].dt.day                              # extract day from datetime column
df['weekday'] = df['date'].dt.day_name()                      # get name of weekday
pd.date_range(start='2024-01-01', periods=5, freq='D')           # generate a range of dates
df.set_index('date').resample('ME').mean(numeric_only=True)        # resample time series data monthly ('ME' = month-end)

             age  is_adult    year  month  day
date
2024-01-31  23.0       1.0  2024.0    1.0  2.0

## 12. Statistics & Math

In [13]:
df['age'].mean()               # average value
df['age'].median()               # median value
df['age'].mode()                   # most frequent value
df['age'].std()                      # standard deviation
df['age'].var()                        # variance
df['age'].min()                          # minimum value
df['age'].max()                            # maximum value
df['age'].sum()                              # sum of values
df['age'].cumsum()                             # cumulative sum
df['age'].corr(df['age'])                        # correlation between two columns
df.corr(numeric_only=True)                          # correlation matrix of numeric columns
df['age'].value_counts()                              # frequency count of unique values

age
23    1
26    1
20    1
Name: count, dtype: int64

## 13. Reshaping Data

In [14]:
df.melt(id_vars=['name'], value_vars=['age'])       # unpivot columns into rows (wide to long)
df.stack()                                             # pivot columns into rows (compress)
df.unstack()                                             # pivot rows into columns (expand)
df.explode('name')                                         # expand list-like column into multiple rows

,name,age,city,is_adult,full_info,date,year,month,day,weekday
0,Ali,23,Lahore,True,Ali - Lahore,2024-01-01,2024,1,1,Monday
1,Sara,26,Karachi,True,Sara - Karachi,2024-01-02,2024,1,2,Tuesday
2,Zain,20,Multan,True,Zain - Multan,2024-01-03,2024,1,3,Wednesday

## 14. Duplicates & Unique Values

In [15]:
df.duplicated()                       # boolean Series: True for duplicate rows
df['name'].unique()                     # array of unique values in a column
df['name'].nunique()                      # count of unique values in a column

3

## 15. Options & Display Settings

In [16]:
pd.set_option('display.max_rows', 100)      # set max number of rows to display
pd.set_option('display.max_columns', 50)      # set max number of columns to display
pd.set_option('display.width', 1000)            # set console display width
pd.reset_option('all')                            # reset all display options to default

/tmp/ipykernel_570/2469529923.py:4: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option('all')                            # reset all display options to default
/tmp/ipykernel_570/2469529923.py:4: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option('all')                            # reset all display options to default

## 16. Copying & Type Conversion

In [17]:
df_copy = df.copy()                    # create a deep copy (avoid modifying original)
df['age'] = df['age'].astype(float)      # convert column data type to float
df['age'] = df['age'].astype(int)          # convert column data type to int
df['name'] = df['name'].astype(str)          # convert column data type to string
df['city'] = df['city'].astype('category')     # convert column to category dtype (saves memory)